[project]
name = "xdoor2"
version = "0.1.0"
dependencies = [
    "asyncssh",
    "cryptography", # replaces ExPublicKey / ex_crypto
    "gpiozero",
    "httpx",
    "paho-mqtt",    # for homeasssitant
]

[project.scripts]
xdoor2 = "xdoor2:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 100

[tool.ruff.format]
docstring-code-format = true
skip-magic-trailing-comma = true
