[project]
name = "xdoor2"
version = "0.1.0"
description = "xdoor but python"
readme = "README.md"
authors = [{ name = "Nicole Heinimann", email = "nicole@heinimann.de" }]
requires-python = ">=3.14"
dependencies = [
    "asyncssh>=2.22.0",
    "cryptography>=47.0.0",  # replaces ExPublicKey / ex_crypto
    "gpiozero>=2.0.1.post3",
    "httpx>=0.28.1",
    "paho-mqtt>=2.1.0",      # for homeasssitant
]

[project.scripts]
xdoor2 = "xdoor2:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pytest>=9.1.1", "pytest-asyncio>=1.4.0", "ruff>=0.16.4", "ty>=0.0.74"]

[tool.ruff]
line-length = 100

[tool.ruff.format]
docstring-code-format = true
skip-magic-trailing-comma = true
